name: CI

on: 
  push:
    branches: [develop]
env:
  DEPLOY_PATH: /var/www/app
  # В теории можно собрать не только Vue-приложение, так как принцип сборки мало где отличаетс6я
  BUILD_SCRIPT: npx create-react-app opa && npx run build
  BUILD_SCRIPT_OUTPUT: '/home/runner/work/testgit/testgit/'
  ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      # Делаем checkout текущей ветки
      - uses: actions/checkout@v2
      # Устанавливаем Node.JS для сборки приложения
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      # Записываем в переменные окружения имя текущей ветки
      # Устанавливаем зависимости для сборки
      - name: Install Dependencies
        run: |
          npm install
      # Собираем приложение
      - name: Build Appliction
        run: |
           npm run build
      # Доставляем собранное приложение на сервер
      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: 51.250.98.41
          port: 22
          username: user
          key: ${{ secrets.DEPLOY_SERVER_KEY }}
          source: ${{ env.BUILD_SCRIPT_OUTPUT }}
          target: ${{ env.DEPLOY_PATH }}/${{ env.BRANCH_NAME }}
          strip_components: 1
      - name: Print Info
        run: echo "Deployed at https://${BRANCH_NAME}.app.example.ru/"
