name: CI-frontend

on: 
  push:
    branches: [develop]
env:
  #место на сервере, куда деплоим проект
  DEPLOY_PATH: /home/user/work
  #место на вирт машине Git, откуда отправляем
  BUILD_SCRIPT_OUTPUT: '/home/runner/work/pets-shelter/pets-shelter/'
  DIR_NAME: frontend-helppet
  ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      # Делаем checkout текущей ветки
      - uses: actions/checkout@v2
      # Устанавливаем Node.JS для сборки приложения
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      # Устанавливаем зависимости для сборки
      - name: Install Dependencies
        run: |
          npm install
      # Собираем приложение
      - name: Build Appliction
        run: |
           npm run build
      # Доставляем собранное приложение на сервер
      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          port: ${{ secrets.DEPLOY_SERVER_PORT }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          key: ${{ secrets.DEPLOY_SERVER_KEY }}
          source: ${{ env.BUILD_SCRIPT_OUTPUT }}
          target: ${{ env.DEPLOY_PATH }}
          strip_components: 1
      - name: Print Info
        run: echo "Success"
